version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_prisma
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: plcrisp
      POSTGRES_PASSWORD: pl123456
      POSTGRES_DB: vipoints
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: